### ISSUE TITLE
Modify Files with Access Restriction

### ISSUE THREAD

**Issue by TheFrazer** [Forceu/Gokapi#210]
When using _Access Restriction_ or _Header Authentication_ as Authentication Method, trying to modify files results in a _401 Unauthorized_ Error.

I reinstalled it with a fresh config, chose _Access Restriction_, uploaded a file, and then tried to modify it (change password, etc.). It returned a 401, too, so it is not a configuration problem.

The request is send to `/api/files/modify`. I would guess that since no user is authenticated it wouldn't work. So when choosing  _Access Restriction_ is it not possible to modify files?

**Comment by Forceu** [comment]
Thanks for your feedback, I will look into it!

**Comment by Forceu** [comment]
Fixed in ddc72b0

**Comment by z1glr** [comment]
For me this still doesn't fully work: I can reach the admin panel without problems. If I start an upload I get a 401 error as soon as the upload is finished (bar reaches end).

I'm on version 2.2.4

**Comment by z1glr** [comment]
To my understanding the frontend makes a request for /auth/token directly after finishing the upload which gets the 401

**Comment by z1glr** [comment]
found it, I needed to add /auth/token to my protected endpoints in my reverse_proxy.
